### ISSUE TITLE
How to use? wiki?

### ISSUE THREAD

**Issue by delkant** [differentway/couchmove#1]
Hello, 

I am trying to use the couchbase branch for jhipster and having some errors with couchmove, but when I come to couchmove's repo there is not documentation on how to use it and configured. the wiki has no content. Any plans for the docs? thanks!

**Comment by tchlyah** [comment]
Hello! 

Sorry about that, I didn't find time to write it, now I'm on vacation and I have no access to a computer! I was planning to write the Doc for Jhipster and Couchbase next week.

Can you please paste here the stack trace you're having? (Even Couchmove errors before), I'll try to help you from here.

**Comment by delkant** [comment]
Thank you so much for your time but I figured it out what was my problem, a "-" in the name of one of my buckets.
