### ISSUE TITLE
Migrate to SDK3

### ISSUE THREAD

**Issue by murdos** [differentway/couchmove#10]
New Spring Data Couchbase release (4.0) uses SDK3.

So lack of support for SKK3 in couchmove will block migration to Spring Boot 2.3 in JHipster.

**Comment by tchlyah** [comment]
I'm actually working on it!

**Comment by vals-productions** [comment]
What is ETA on this upgrade? Really like this framework.

**Comment by tchlyah** [comment]
Thanks @vals-productions ! Sorry for the delay, I was working on it but then I had a 👶, I can hardly sleep so maintaining this projet is hard

I'm almost done, I have some failing tests that I need to fix. I'll push my work if you want to help me

**Comment by murdos** [comment]
@tchlyah : Thanks! And don't worry, I'll take care of the integration to jhipster 😉

**Comment by vals-productions** [comment]
I tried 3.0-SNAPSHOT and it worked for me in a scope of create index and a couple of insert statements. I had to change initialization code in CouchbaseConfig to: 
```java
@Configuration
public class CouchbaseConfig extends AbstractCouchbaseConfiguration {
...
    @Bean
	public Couchmove couchmove(/*Bucket bucket*/) {
    	com.couchbase.client.java.Bucket bucket = cluster.bucket(getBucketName());
        Couchmove couchmove = new Couchmove(bucket, cluster, "cp_couchmove");
        couchmove.migrate();
        return couchmove;
    }
```
as Spring refused to wire Bucket as a parameter. I might be able to help with the project but will need more info on environment setup. Tests that still fail were docker related.

**Comment by murdos** [comment]
@tchlyah : I've not encountered any particular issue with the snapshot version. Would you mind doing an official 3.0 release?

**Comment by tchlyah** [comment]
@murdos done!
Thanks a lot for your help
