### ISSUE TITLE
FTS with custom type mapping not working in couchmove 3.0

### ISSUE THREAD

**Issue by bhattrahul2309** [differentway/couchmove#12]
With new couchmove 3.0, I am not able to create FTS index , where I have to create FTS index using custom type_field, and type mappings. The same FTS json was working fine in earlier couchmove 2.0 release.
As I want to narrow down the FTS, only with specific attributes having the required value. 
Please provide your inputs.

Below the .fts file content under /db/migration, which I am trying to create.

**{
  "name": "problemSearch",
  "type": "fulltext-index",
  "params": {
    "doc_config": {
      "docid_prefix_delim": "",
      "docid_regexp": "",
      "mode": "type_field",
      "type_field": "_class"
    },
    "mapping": {
      "default_analyzer": "standard",
      "default_datetime_parser": "dateTimeOptional",
      "default_field": "_all",
      "default_mapping": {
        "dynamic": true,
        "enabled": false
      },
      "default_type": "_default",
      "docvalues_dynamic": true,
      "index_dynamic": true,
      "store_dynamic": false,
      "type_field": "_type",
      "types": {
        "com.bhatt.avengers.supermmanagement.entity.Problem": {
          "dynamic": true,
          "enabled": true
        }
      }
    },
    "store": {
      "indexType": "scorch",
      "kvStoreName": ""
    }
  },
  "sourceType": "couchbase",
  "sourceName": "fault_management"
}**

**Comment by gilb77** [comment]
I have the same problem, someone can help?

**Comment by gkysaad** [comment]
I've created a PR to fix this issue:
https://github.com/differentway/couchmove/pull/13

**Comment by tchlyah** [comment]
@gkysaad, in case you didn't notice, version [3.1.1-SNAPSHOT](https://oss.sonatype.org/service/local/repositories/snapshots/content/com/github/differentway/couchmove/3.1.1-SNAPSHOT/couchmove-3.1.1-20210616.222312-1.pom) has been automatically pushed when I merged the PR.

I'll push a final version as soon as you validate that everything is working as expected.

**Comment by gkysaad** [comment]
Thanks, I've tried the snapshot and everything seems to be working as expected.

**Comment by tchlyah** [comment]
Version [3.1.1](https://ossindex.sonatype.org/component/pkg:maven/com.github.differentway/couchmove@3.1.1) released
