### ISSUE TITLE
add "wait for" functionality

### ISSUE THREAD

**Issue by vals-productions** [differentway/couchmove#19]
Seems like an enhancement would be helpful in regards to how scopes and collections work.

The following script will fail:
```
CREATE SCOPE bucket.scope;
CREATE COLLECTION bucket.scope.collection;
INSERT INTO bucket.scope.collection...
```
because the first statement returns before the scope was actually created. And the second one will not find a scope to add a collection to. If it manages to execute the second line because the scope somehow was created very fast then the third insert will fail if the collection might not be available yet.

This is reproducible within couchmove and even couchbase admin tool query.

If would be nice to add a function like

WAIT_UNTIL(select list of scopes where scope = '...' );

that will loop until the statement returns at least one record.

**Comment by tchlyah** [comment]
This is already handled by a backoff retry when we are detecting this kind of error ([12003: keyspace not found](https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/n1ql-error-codes.html#12xxx-codes-ds_cb), [12021: Scope not found](https://review.couchbase.com/plugins/gitiles/query/+/c503001cfae14c52b6cac916e109bea9088aa52d/errors/ds_couchbase.go#116)). See [here].(https://github.com/differentway/couchmove/blob/b9e49a288afb5da117dda6d1f5756804370da025/src/main/java/com/github/couchmove/repository/CouchbaseRepositoryImpl.java#L204)

I'm using in JHipster and it works fine.
