### ISSUE TITLE
Apply migrations from several nodes

### ISSUE THREAD

**Issue by kao73** [differentway/couchmove#4]
Hello,

Thank you for the great product, first of all!
We've faced with a problem to apply migrations from two nodes of a single service.
First node creates an index once started, which is ok. The second node starts later and doesn't know if the index already created. Thus, the second node fails with error like "index already created".
Looks like first node created changelog record successfully, but before the second node tested it.
I wonder if you have some mechanism to synchronize nodes?

Thanks,

**Comment by tchlyah** [comment]
Hello,

Thanks for your kind words !

This shouldn't happen. Actually, Couchmove try to get a lock by setting a changelog lock document using optimistic locking before executing the changelogs, then release it.

What is your Bucket consistency configuration? If you are using Couchbase SDK it should be [REQUEST_PLUS](https://docs.couchbase.com/java-sdk/2.7/scan-consistency-examples.html). If you're using Spring Data Couchbase it should be  [STRONGLY_CONSISTENT](https://www.baeldung.com/entity-validation-locking-and-query-consistency-in-spring-data-couchbase#1-levels-of-consistency)

**Comment by kao73** [comment]
Hello,

Thanks for support.
I'm using Spring Data Couchbase with STRONGLY_CONSISTENT configuration.

I found the problem is kind of race conditions.
We start two service nodes at the same time. Migration starts correctly on the first node, but when the second node tries to acquire lock it throws exception, because the lock is not released by the first node.
Do you have some handling for such cases?

Thanks.

**Comment by tchlyah** [comment]
Hello,

Yes this is how it is implemented for now. If Couchmove can't get the lock, it fails. We should implement a waiting with timeout until the first node releases the lock.

I'll try to do it when I have time, but contributions  are welcome 😊

**Comment by kao73** [comment]
:) makes sense
I will try to implement a try/catch block around migrate() call to retry migration several times.
Another option I see is to start nodes with delay.
That will resolve my problem for the first time.

Thanks for support and for the offer. Will try to find some time to contribute if possible :)

Alexey.
